version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - es:/usr/share/elasticsearch/data
  kibana:
    image: kibana:6.5.4
    container_name: kibana
    ports:
      - "5601:5601"
volumes:
  es:
    driver: local
